_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-x86_64
activation:
    value: relu
batch_size:
    value: 32
cnn_kernel_size_1:
    value: 2
cnn_kernel_size_2:
    value: 3
cnn_layers:
    value: 1
data_path:
    value: workspace/Processed Datasets/CB06.03.015_ssd_01D997.csv
dense_units:
    value: 256
dilation_rate_1:
    value: 1
dilation_rate_2:
    value: 2
epochs:
    value: 50
filters_1:
    value: 128
filters_2:
    value: 32
history_length:
    value: 1
history_path:
    value: workspace/t/Model Training History/CB06.03.015_ssd_01D997
input_type:
    value: multivariate
kernel_size_1:
    value: 7
kernel_size_2:
    value: 7
learning_rate:
    value: 0.04105020795814357
lstm_layers:
    value: 5
lstm_units:
    value: 32
model_type:
    value: CNNModel
optimizer:
    value: adam
prediction_length:
    value: 1
probabilistic:
    value: false
save_path:
    value: workspace/t/Model Weights/CB06.03.015_ssd_01D997
target_column:
    value: t
