_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 2
                - 3
                - 8
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.5
            "8":
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.5
            "13": darwin-x86_64
activation:
    value: relu
batch_size:
    value: 32
cnn_kernel_size_1:
    value: 1
cnn_kernel_size_2:
    value: 3
cnn_layers:
    value: 3
data_path:
    value: workspace/Processed Datasets/CB06.03.015_ssd_01D997.csv
dense_units:
    value: 128
dilation_rate_1:
    value: 4
dilation_rate_2:
    value: 4
epochs:
    value: 50
filters_1:
    value: 64
filters_2:
    value: 64
history_length:
    value: 1
history_path:
    value: workspace/t/Model Training History/CB06.03.015_ssd_01D997
input_type:
    value: univariate
kernel_size_1:
    value: 3
kernel_size_2:
    value: 5
learning_rate:
    value: 0.03138527823160029
lstm_layers:
    value: 4
lstm_units:
    value: 64
model_type:
    value: CNNModel
optimizer:
    value: adamax
prediction_length:
    value: 1
probabilistic:
    value: false
save_path:
    value: workspace/t/Model Weights/CB06.03.015_ssd_01D997
target_column:
    value: t
