wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
cnn_kernel_size_1:
  value: 3
cnn_kernel_size_2:
  value: 3
cnn_layers:
  value: 2
data_path:
  value: workspace/Processed Datasets/CB06.03.015_ssd_01D997.csv
dense_units:
  value: 128
dilation_rate_1:
  value: 4
dilation_rate_2:
  value: 4
epochs:
  value: 50
filters_1:
  value: 64
filters_2:
  value: 128
history_length:
  value: 1
history_path:
  value: workspace/t/Model Training History/CB06.03.015_ssd_01D997
input_type:
  value: univariate
kernel_size_1:
  value: 7
kernel_size_2:
  value: 5
learning_rate:
  value: 0.07738870237146107
lstm_layers:
  value: 2
lstm_units:
  value: 32
model_type:
  value: CNNModel
optimizer:
  value: adam
prediction_length:
  value: 1
probabilistic:
  value: false
save_path:
  value: workspace/t/Model Weights/CB06.03.015_ssd_01D997
target_column:
  value: t
track_file:
  value: workspace/t/Performance Tracking/model_performance_tracking_CB06.03.015_ssd_01D997.json
