wandb_version: 1

activation:
  value: selu
batch_size:
  value: 64
cnn_kernel_size_1:
  value: 3
cnn_kernel_size_2:
  value: 2
cnn_layers:
  value: 4
data_path:
  value: workspace/Processed Datasets/CB06.03.015_ssd_01D997.csv
dense_units:
  value: 256
dilation_rate_1:
  value: 2
dilation_rate_2:
  value: 1
epochs:
  value: 50
filters_1:
  value: 128
filters_2:
  value: 64
history_length:
  value: 1
history_path:
  value: workspace/t/Model Training History/CB06.03.015_ssd_01D997
input_type:
  value: univariate
kernel_size_1:
  value: 5
kernel_size_2:
  value: 3
learning_rate:
  value: 0.05103181438978812
lstm_layers:
  value: 2
lstm_units:
  value: 128
model_type:
  value: CNNModel
optimizer:
  value: adadelta
prediction_length:
  value: 1
probabilistic:
  value: false
save_path:
  value: workspace/t/Model Weights/CB06.03.015_ssd_01D997
target_column:
  value: t
track_file:
  value: workspace/t/Performance Tracking/model_performance_tracking_CB06.03.015_ssd_01D997.json
