wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 32
cnn_kernel_size_1:
  value: 1
cnn_kernel_size_2:
  value: 3
cnn_layers:
  value: 5
data_path:
  value: workspace/Processed Datasets/CB06.03.015_ssd_01D997.csv
dense_units:
  value: 128
dilation_rate_1:
  value: 1
dilation_rate_2:
  value: 1
epochs:
  value: 50
filters_1:
  value: 32
filters_2:
  value: 128
history_length:
  value: 1
history_path:
  value: workspace/t/Model Training History/CB06.03.015_ssd_01D997
input_type:
  value: univariate
kernel_size_1:
  value: 3
kernel_size_2:
  value: 3
learning_rate:
  value: 0.08301890972418588
lstm_layers:
  value: 3
lstm_units:
  value: 64
model_type:
  value: CNNModel
optimizer:
  value: adagrad
prediction_length:
  value: 1
probabilistic:
  value: false
save_path:
  value: workspace/t/Model Weights/CB06.03.015_ssd_01D997
target_column:
  value: t
